### ISSUE TITLE
Stemmer Kalimat

### ISSUE THREAD

**Issue by irsalshabirin** [jsastrawi/jsastrawi#2]
di php ada yang stemming dengan input kalimat ataupun perkata, sedangkan yang dijava masih hanya bisa kata aja ya mas ?

terima kasih 👍 👍 👍 👍 👍 👍

**Comment by andylibrian** [comment]
Betul mas, yang di java ini lebih baru dari versi php. Memang semestinya
stemmer itu cukup untuk kata saja. Karena untuk memecah kalimat ke kata,
butuh algoritma lain, biasanya menjadi tugas komponen lain: tokenizer.

Jadi sengaja saya buang fungsi untuk stem kalimat. Untuk memecah kalimat
menjadi kata, gunakan tokenizer. Kemudian masing-masing kata distem.

**Comment by irsalshabirin** [comment]
ok mas, :) terima kasih 👍
